name: dvd
channels:
  - kne  # for pybox2d
  - pytorch
  - anaconda  # for mkl
  - conda-forge
dependencies:
  - cython
  - ipython  # technically unnecessary
  - lockfile
  - mako=1.0.6=py35_0
  - mkl=2018.0.2  # Need to add explicit dependence for pytorch
  - numpy=1.11.3
  - path.py=10.3.1=py35_0
  - python=3.5.2
  - python-dateutil=2.6.1=py35_0
  - pytorch=1.0.1
  - scipy=1.0.1
  - patchelf        # Linux only; comment this line out for Mac
  - swig
  - pip:
      - cloudpickle==0.5.2
      - glfw
      - gym[all]==0.10.5
      - gitpython==2.1.7
      - gtimer==1.0.0b5
      - pygame==1.9.2
      - box2d        # Linux only; comment this line out for Mac
      - box2d-kengz  # Linux only; comment this line out for Mac
      - protobuf==3.9.2
      - tensorboardX==1.6
      - click
      - joblib==0.9.4
      - matplotlib==2.0.2
      - numba==0.35.0
