name: dvd
channels:
  - kne  # for pybox2d
  - pytorch
  - anaconda  # for mkl
dependencies:
  - cython
  - ipython  # technically unnecessary
  - lockfile
  - mkl=2018.0.2  # Need to add explicit dependence for pytorch
  - numpy=1.11.3
  - pytorch=1.0.1
  - torchvision
  - scipy=1.0.1
  - patchelf        # Linux only; comment this line out for Mac
  - matplotlib=2.0.2
  - python=3.7
  # - path.py=10.3.1=py35_0
  # - python=3.5.2
  # - python-dateutil=2.6.1=py35_0
  # - numba=0.35.0=np111py35_0
  # - mako=1.0.6=py35_0
  - pip:
      - cloudpickle==0.5.2
      - glfw
      - gym[all]==0.10.5
      - gitpython==2.1.7
      - gtimer==1.0.0b5
        # - pygame==1.9.2
      - box2d        # Linux only; comment this line out for Mac
      - box2d-kengz  # Linux only; comment this line out for Mac
      - tensorboardX==1.6
      - click
      - joblib==0.9.4
        # - matplotlib==2.0.2=np111py35_0
      - path.py==10.3.1
        # - python==3.5.2
      - python-dateutil==2.6.1
      - numba==0.35.0
      - mako==1.0.6
      - av
      - opencv-python
      - h5py
      - pyquaternion
